apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ken-dev-view
  namespace: dev
subjects: 
- kind: ServiceAccount
  name: ken
  namespace: dev
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.iocurl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt