apiVersion: v1
kind: Pod
metadata:
  name: nginx-otus-kp
  labels:
    name: nginx-otus-kp
spec:
  containers:
  - name: nginx-otus-kp
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
    - name: busybox-wget
      image: busybox:latest
      command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
      volumeMounts:
        - name:  app
          mountPath:  /app
  volumes:  
    - name: app
      emptyDir: {}

